# Generated by Django 5.1.4 on 2026-01-03 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free', 'رایگان آزمایشی (۵ روز)'), ('basic', 'پایه – ماهانه'), ('pro', 'حرفه\u200cای – ماهانه')], max_length=20, unique=True, verbose_name='کد سیستمی پلن')),
                ('name', models.CharField(max_length=50, verbose_name='نام نمایشی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات (برای نمایش در صفحه خرید)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('days', models.PositiveSmallIntegerField(default=30, verbose_name='مدت اعتبار (روز)')),
                ('max_products', models.PositiveSmallIntegerField(default=10, verbose_name='حداکثر تعداد محصول')),
                ('max_orders_per_month', models.PositiveIntegerField(default=100, verbose_name='سقف سفارش ماهانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل خرید')),
                ('is_default', models.BooleanField(default=False, verbose_name='پلن پیش\u200cفرض ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='شناسه در URL')),
                ('instagram_username', models.CharField(max_length=100, unique=True, verbose_name='آیدی اینستاگرام')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی کوتاه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس پشتیبانی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس فروشگاه (اختیاری)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فروشگاه')),
                ('enable_cod', models.BooleanField(default=True, verbose_name='پرداخت در محل')),
                ('enable_card_to_card', models.BooleanField(default=False, verbose_name='کارت به کارت')),
                ('card_owner_name', models.CharField(blank=True, max_length=100, verbose_name='نام صاحب کارت')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت')),
                ('shaba_number', models.CharField(blank=True, max_length=26, verbose_name='شماره شبا')),
                ('enable_online_payment', models.BooleanField(default=False, verbose_name='پرداخت آنلاین (زرین\u200cپال)')),
                ('zarinpal_merchant_id', models.CharField(blank=True, max_length=36, verbose_name='مرچنت کد زرین\u200cپال')),
                ('plan_started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع اشتراک')),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای اشتراک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تاسیس')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.plan', verbose_name='پلن فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فروشگاه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
            },
        ),
    ]
