# Generated by Django 5.1.4 on 2026-01-07 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price'], 'verbose_name': 'پلن اشتراک', 'verbose_name_plural': 'پلن\u200cهای اشتراک'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه\u200cها'},
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='پلن پرطرفدار'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free', 'رایگان آزمایشی (۵ روز)'), ('basic', 'پایه – ماهانه'), ('pro', 'حرفه\u200cای – ماهانه'), ('enterprise', 'سازمانی – سالانه')], max_length=20, unique=True, verbose_name='کد سیستمی پلن'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.plan', verbose_name='پلن فعال'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/%Y/%m/', verbose_name='لوگو'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['code', 'is_active'], name='shops_plan_code_782133_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['price', 'is_active'], name='shops_plan_price_942853_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug', 'is_active'], name='shops_shop_slug_eecfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['instagram_username'], name='shops_shop_instagr_17e25f_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at'], name='shops_shop_created_8bca73_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['plan_expires_at'], name='shops_shop_plan_ex_b39d56_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['current_plan', 'plan_expires_at'], name='shops_shop_current_e3072e_idx'),
        ),
    ]
