# Generated by Django 5.2.9 on 2025-12-25 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_plan_alter_shop_options_remove_shop_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price'], 'verbose_name': 'پلن اشتراک', 'verbose_name_plural': 'پلن\u200cهای اشتراک'},
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات (برای نمایش در صفحه خرید)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='پلن پیش\u200cفرض ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='لوگو'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free', 'رایگان آزمایشی (۵ روز)'), ('basic', 'پایه – ماهانه'), ('pro', 'حرفه\u200cای – ماهانه')], max_length=20, unique=True, verbose_name='کد سیستمی پلن'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='مدت اعتبار (روز)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='قابل خرید'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_products',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='حداکثر تعداد محصول'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس فروشگاه (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bio',
            field=models.TextField(blank=True, verbose_name='بیوگرافی کوتاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تاسیس'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='enable_online_payment',
            field=models.BooleanField(default=False, verbose_name='پرداخت آنلاین (زرین\u200cپال)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='شناسه در URL'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فروشگاه'),
        ),
    ]
