# Generated by Django 5.1.4 on 2026-01-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی گیرنده')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس کامل پستی')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('city', models.CharField(default='', max_length=50, verbose_name='شهر')),
                ('province', models.CharField(default='', max_length=50, verbose_name='استان')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده'), ('refunded', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cash', 'پرداخت در محل'), ('bank', 'کارت به کارت')], default='online', max_length=20, verbose_name='روش پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کل (ریال)')),
                ('shipping_method', models.CharField(default='پست پیشتاز', max_length=50, verbose_name='روش ارسال')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد در لحظه خرید')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='نام محصول')),
                ('variant_info', models.CharField(blank=True, max_length=200, verbose_name='اطلاعات تنوع')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='order_items/', verbose_name='عکس محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='تنوع انتخاب شده')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
    ]
