# Generated by Django 5.2.9 on 2025-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='shop',
            name='card_owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام صاحب کارت'),
        ),
        migrations.AddField(
            model_name='shop',
            name='enable_card_to_card',
            field=models.BooleanField(default=False, verbose_name='فعالسازی کارت به کارت'),
        ),
        migrations.AddField(
            model_name='shop',
            name='enable_cod',
            field=models.BooleanField(default=True, verbose_name='فعالسازی پرداخت در محل'),
        ),
        migrations.AddField(
            model_name='shop',
            name='enable_online_payment',
            field=models.BooleanField(default=False, verbose_name='فعالسازی درگاه آنلاین'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=26, verbose_name='شماره شبا (اختیاری)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='zarinpal_merchant_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='مرچنت کد زرین\u200cپال'),
        ),
    ]
