# Generated by Django 5.2.9 on 2025-12-25 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_card_number_shop_card_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free', 'رایگان ۷ روزه'), ('basic', 'پایه – ماهانه'), ('pro', 'حرفه\u200cای – ماهانه')], max_length=10, unique=True, verbose_name='کد پلن')),
                ('name', models.CharField(max_length=50, verbose_name='نام نمایشی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('days', models.PositiveSmallIntegerField(verbose_name='مدت روزها')),
                ('max_products', models.PositiveSmallIntegerField(default=10, verbose_name='حداکثر محصولات')),
                ('max_orders_per_month', models.PositiveIntegerField(default=100, verbose_name='سقف سفارش ماهانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای فروش')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shop',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای اشتراک'),
        ),
        migrations.AddField(
            model_name='shop',
            name='plan_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع اشتراک'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bio',
            field=models.TextField(blank=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='enable_card_to_card',
            field=models.BooleanField(default=False, verbose_name='کارت به کارت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='enable_cod',
            field=models.BooleanField(default=True, verbose_name='پرداخت در محل'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='enable_online_payment',
            field=models.BooleanField(default=False, verbose_name='پرداخت آنلاین'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram_username',
            field=models.CharField(max_length=100, unique=True, verbose_name='آیدی اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=26, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.plan', verbose_name='پلن فعال'),
        ),
    ]
