# Generated by Django 5.1.4 on 2026-01-07 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_alter_plan_options_alter_shop_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCleanupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ADMIN_LOG', 'لاگ ادمین'), ('SHOP_ACTIVITY', 'فعالیت فروشگاه'), ('SYSTEM_LOG', 'لاگ سیستم'), ('API_LOG', 'لاگ API')], max_length=20, verbose_name='نوع کار')),
                ('retention_days', models.IntegerField(default=90, verbose_name='روزهای نگهداری')),
                ('batch_size', models.IntegerField(default=1000, verbose_name='اندازه بچ')),
                ('deleted_count', models.IntegerField(default=0, verbose_name='تعداد حذف شده')),
                ('error_count', models.IntegerField(default=0, verbose_name='تعداد خطا')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('is_success', models.BooleanField(default=False, verbose_name='موفقیت\u200cآمیز')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
            ],
            options={
                'verbose_name': 'کار پاک\u200cسازی لاگ',
                'verbose_name_plural': 'کارهای پاک\u200cسازی لاگ',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'دیباگ'), ('INFO', 'اطلاعات'), ('WARNING', 'هشدار'), ('ERROR', 'خطا'), ('CRITICAL', 'بحرانی')], max_length=10, verbose_name='سطح')),
                ('component', models.CharField(choices=[('AUTH', 'احراز هویت'), ('SHOP', 'فروشگاه'), ('PAYMENT', 'پرداخت'), ('EMAIL', 'ایمیل'), ('API', 'API'), ('DATABASE', 'دیتابیس'), ('TASK', 'تسک'), ('CACHE', 'کش'), ('SECURITY', 'امنیت'), ('MONITORING', 'مانیتورینگ')], max_length=20, verbose_name='کامپوننت')),
                ('message', models.TextField(verbose_name='پیام')),
                ('traceback', models.TextField(blank=True, verbose_name='تریس\u200cبک')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cها')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='نام هاست')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه پروسه')),
                ('thread_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه ترد')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لاگ سیستم',
                'verbose_name_plural': 'لاگ\u200cهای سیستم',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', '-timestamp'], name='logs_system_level_633399_idx'), models.Index(fields=['component', '-timestamp'], name='logs_system_compone_c02121_idx'), models.Index(fields=['timestamp'], name='logs_system_timesta_1ce06b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'ویرایش'), ('DELETE', 'حذف'), ('LOGIN', 'ورود'), ('LOGOUT', 'خروج'), ('EXPORT', 'اکسپورت'), ('IMPORT', 'ایمپورت'), ('ACTION', 'عملیات'), ('ERROR', 'خطا'), ('WARNING', 'هشدار'), ('INFO', 'اطلاعات')], max_length=50, verbose_name='نوع عملیات')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه شیء')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='داده قبلی')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='داده جدید')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='مسیر')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='متد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'لاگ ادمین',
                'verbose_name_plural': 'لاگ\u200cهای ادمین',
                'ordering': ['-timestamp'],
                'permissions': [('view_admin_log', 'مشاهده لاگ ادمین'), ('export_admin_log', 'اکسپورت لاگ ادمین'), ('clear_old_logs', 'پاک کردن لاگ\u200cهای قدیمی')],
                'indexes': [models.Index(fields=['admin', '-timestamp'], name='logs_adminl_admin_i_8cca56_idx'), models.Index(fields=['action', '-timestamp'], name='logs_adminl_action_32be9a_idx'), models.Index(fields=['model', '-timestamp'], name='logs_adminl_model_d56bc5_idx'), models.Index(fields=['ip_address', '-timestamp'], name='logs_adminl_ip_addr_7b5014_idx'), models.Index(fields=['timestamp'], name='logs_adminl_timesta_94348b_idx')],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, verbose_name='متد')),
                ('path', models.CharField(max_length=500, verbose_name='مسیر')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='پارامترهای کوئری')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='هدرها')),
                ('status_code', models.IntegerField(verbose_name='کد وضعیت')),
                ('response_time', models.FloatField(verbose_name='زمان پاسخ (ثانیه)')),
                ('response_size', models.IntegerField(default=0, verbose_name='حجم پاسخ (بایت)')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('error_traceback', models.TextField(blank=True, verbose_name='تریس\u200cبک خطا')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, verbose_name='مرجع')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ API',
                'verbose_name_plural': 'لاگ\u200cهای API',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['method', '-timestamp'], name='logs_apilog_method_44bb2e_idx'), models.Index(fields=['status_code', '-timestamp'], name='logs_apilog_status__348f6e_idx'), models.Index(fields=['user', '-timestamp'], name='logs_apilog_user_id_75311b_idx'), models.Index(fields=['ip_address', '-timestamp'], name='logs_apilog_ip_addr_f9c3d6_idx'), models.Index(fields=['timestamp'], name='logs_apilog_timesta_ad188c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PLAN', 'اشتراک'), ('PRODUCT', 'محصول'), ('ORDER', 'سفارش'), ('CUSTOMER', 'مشتری'), ('SETTINGS', 'تنظیمات'), ('USER', 'کاربر'), ('PAYMENT', 'پرداخت'), ('SYSTEM', 'سیستم')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('action', models.CharField(max_length=100, verbose_name='عملیات')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='کلید سشن')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='shops.shop', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت فروشگاه',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت فروشگاه',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['shop', '-timestamp'], name='logs_shopac_shop_id_6f921f_idx'), models.Index(fields=['category', '-timestamp'], name='logs_shopac_categor_a4d0ff_idx'), models.Index(fields=['user', '-timestamp'], name='logs_shopac_user_id_6d2225_idx'), models.Index(fields=['action', '-timestamp'], name='logs_shopac_action_36307b_idx')],
            },
        ),
    ]
