# Generated by Django 5.2.9 on 2025-12-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه در URL')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت پایه (ریال)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='جنس')),
                ('images', models.JSONField(default=list, verbose_name='تصاویر محصول')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='سایز')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('price_adjustment', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='افزایش قیمت (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع (رنگ/سایز)',
                'verbose_name_plural': 'تنوع\u200cهای محصول',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='products_pr_shop_id_44685a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
